import os

base = r"c:\Users\admin\Desktop\backup\Projects\Gemini Projects\WhatDoesItMean"

dirs = [
    "specs",
    "specs/common",
    "specs/modules",
    "specs/modules/core",
    "specs/modules/ui",
    "src",
    "tests",
    ".human",
]

for d in dirs:
    os.makedirs(os.path.join(base, d), exist_ok=True)

files = {
    ".geminiignore": ".human/\n",
    ".human/shortcuts.md": "# Shortcuts\n- `You are drifting, re-read the spec URI: spec://...`\n- `Update the WAL.`\n",
    "GEMINI.md": "# Gemini AI Entry Sequence\n1. ALWAYS read `specs/BOOT.md` first at the start of any new session or context switch.\n2. Do NOT ignore the protocols within `specs/`.\n",
    "specs/BOOT.md": """# System BOOT sequence
1. Read `specs/WAL.md` to understand the current continuation state.
2. Read the specs linked in the `WAL.md` 'In Progress' section.
3. NEVER assume context from memory. ALWAYS rely on files.
4. Keep actions atomic, referencing spec URIs (e.g., `spec://whatdoesitmean/core/PROP-001#hotkey.trigger`).
5. AI MUST NOT leave overt indicators of its presence in the codebase (no "Generated by AI" comments, etc.).
""",
    "specs/WAL.md": """## Current Phase
PROP-000: Project Foundation — IN PROGRESS

## Completed
- Created initial IPC structure.

## In Progress
- PROP-000 (Foundational decisions) `spec://whatdoesitmean/common/PROP-000`

## Known Issues
None.

## Decisions Pending
- Human validation of project architecture.

## Session Context
Start: Project initialized based on the Coprocessor model.
Next: Define core specs in `PROP-001.md`.
""",
    "specs/WAL-PROTOCOL.md": """# WAL Protocol
1. **Update Frequency**: Update `WAL.md` at the end of every session, before any destructive operation, or when switching contexts.
2. **Size constraint**: Keep `WAL.md` under 3000 tokens. Collapse completed items into single lines.
3. **Structure**: Must contain `Current Phase`, `Completed`, `In Progress`, `Known Issues`, `Decisions Pending`, and `Session Context`.
""",
    "specs/SPEC-PROTOCOL.md": """# Specification Protocol
1. **Hierarchy**: Human > Specs > Tests > Code.
2. **Conflict Resolution**: If AI disagrees with a spec, implement the spec as written, add `<!-- REVIEW: [reason] -->` in the spec, and report to human. NEVER rewrite the spec silently.
3. **Addressability**: All specs must use URIs `spec://<module>/<doc>#<section>`.
4. **Visibility**: Read fresh state. Do not rely on cache.
5. **AI Stealth Mode**: AI models and LLMs (including this agent) MUST NOT leave definitive indicators that code was generated using AI. This includes Git commit messages (`co-authored-by`), comments in code, READMEs, and service docs, unless explicitly approved by the human. Technical instructions for AI within `specs/` are allowed.
""",
    "specs/common/PROP-000.md": """# PROP-000: Foundational Decisions {#root}

## 1. Stack {#stack}
- Language: Python 3
- UI: `customtkinter`
- Hotkeys: `keyboard` package
- Clipboard tracking: `pyperclip`
- LLM Integration: `google-generativeai` (Gemini Flash model)

## 2. Architecture {#architecture}
A background process listens for a globally registered shortcut. Upon trigger, it captures highlighted text (via Ctrl+C injection), queries the LLM, and spawns a customtkinter popup with the response.

## 3. Style and Conventions {#style}
- Use atomic development linked to spec URIs.
- Strict adherence to SPEC-PROTOCOL.md and WAL-PROTOCOL.md.
""",
    "specs/common/main.md": """# Main Architecture
WordExplainer (WhatDoesItMean) is a standalone Windows Python application that utilizes the Gemini API to explain highlighted text triggered by a global user shortcut.
""",
}

for rel_path, content in files.items():
    with open(os.path.join(base, rel_path), "w", encoding="utf-8") as f:
        f.write(content)

print(f"Scaffolded {len(files)} files and {len(dirs)} directories successfully.")
